import { GoogleGenAI, Type } from "@google/genai";
import { ContentType, ScanResult, ApiDetail } from '../types';

// Initialize the client with the API key injected via Vite's define config
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const MANUAL_TIPS = {
    [ContentType.TEXT]: [
        "Check for repetitive sentence structures or phrases.",
        "Look for overly complex words used unnecessarily.",
        "Does the text lack a personal voice, emotion, or anecdotes?",
        "Verify factual claims from independent, reputable sources."
    ],
    [ContentType.IMAGE]: [
        "Zoom in on details like hands, teeth, and text in the background.",
        "Examine shadows, reflections, and light sources for consistency.",
        "Look for strange blurring, unnatural textures, or mismatched patterns.",
        "Use a reverse image search to find the image's origin or similar versions."
    ],
    [ContentType.VIDEO]: [
        "Check for unnatural facial movements or blinking patterns.",
        "Listen for robotic-sounding speech or audio that doesn't match the lip movements.",
        "Look for flickering or distortions around the edges of objects or people.",
        "Are there any weird blurs or 'morphing' effects during movement?"
    ]
};

export const scanContent = async (
    type: ContentType,
    data: string | string[], // data is always string (text or base64) or string[] (video frames)
    fileName?: string,
    mimeType?: string // mimeType is passed for images
): Promise<ScanResult> => {

    try {
        let contents: any;
        let systemInstruction = "";

        // Define the schema for the structured output using the SDK's Type enum
        const responseSchema = {
            type: Type.OBJECT,
            properties: {
                aiScore: { type: Type.NUMBER, description: "A score from 0 (definitely human) to 100 (definitely AI)." },
                reasoning: { type: Type.STRING, description: "A brief, one-sentence explanation for the score." },
                evidence: {
                    type: Type.ARRAY,
                    description: "A list of 2-3 bullet points detailing specific evidence found in the content.",
                    items: { type: Type.STRING }
                }
            },
            required: ["aiScore", "reasoning", "evidence"],
        };

        if (type === ContentType.TEXT && typeof data === 'string') {
            systemInstruction = "You are an expert AI content detector. Analyze the following text and determine the probability that it was generated by an AI. Provide a score from 0 to 100 and detailed reasoning in the requested JSON format.";
            contents = {
                parts: [
                    { text: "Here is the text to analyze:" },
                    { text: data }
                ]
            };
        } else if (type === ContentType.IMAGE && typeof data === 'string') {
            systemInstruction = "You are an expert AI-generated image detector. Analyze the following image for signs of AI generation, such as artifacts in hands, text, shadows, or textures. Provide a score from 0 to 100 and detailed reasoning in the requested JSON format.";
            contents = {
                parts: [
                    { text: "Here is the image to analyze:" },
                    { inlineData: { mimeType: mimeType || 'image/jpeg', data: data } }
                ]
            };
        } else if (type === ContentType.VIDEO && Array.isArray(data)) {
            systemInstruction = "You are an expert AI-generated video detector. I will provide you with a sequence of frames extracted from a video. Analyze these frames as a whole for common signs of AI generation (e.g., flickering, morphing artifacts, unnatural movement, inconsistent details). Provide a single, overall score for the entire video based on these frames and detailed reasoning in the requested JSON format.";
            const parts: any[] = [{ text: "Here are the frames to analyze:" }];
            data.forEach(frameBase64 => {
                parts.push({ inlineData: { mimeType: 'image/jpeg', data: frameBase64 } });
            });
            contents = { parts };
        } else {
             throw new Error("Invalid data format for the selected content type.");
        }

        // Execute the request using the correct Gemini 2.5 Flash model
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents,
            config: {
                systemInstruction,
                responseMimeType: "application/json",
                responseSchema,
            },
        });

        const jsonText = response.text?.trim();

        if (!jsonText) {
            throw new Error('The AI model returned an empty response. This may be due to content safety filters or a temporary issue.');
        }

        let result;
        try {
            result = JSON.parse(jsonText);
        } catch (e) {
            console.error("Failed to parse JSON from Gemini:", jsonText);
            throw new Error(`Failed to parse analysis results.`);
        }

        const analysis: ApiDetail[] = [{
            provider: 'Gemini AI',
            score: Number(result.aiScore),
            details: [result.reasoning, ...result.evidence]
        }];
        
        const scanResult: ScanResult = {
            overallScore: parseFloat(Number(result.aiScore).toFixed(2)),
            contentType: type,
            analysis: analysis,
            manualInspectionTips: MANUAL_TIPS[type],
            fileName: fileName,
        };

        return scanResult;

    } catch (error: any) {
        console.error("Error in detection service:", error);
        throw new Error(error.message || "Failed to communicate with the analysis service. Please try again.");
    }
};