import { GoogleGenAI } from "@google/genai";
import { ContentType, ScanResult, ApiDetail } from '../types';

// This is a Vercel Serverless Function. 
// It will handle requests to /api/scan.
// req.body will be automatically parsed by Vercel for JSON requests.
export default async function handler(req, res) {
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method Not Allowed' });
    }

    const API_KEY = process.env.API_KEY as string;
    if (!API_KEY) {
        console.error("API_KEY environment variable not set on the server.");
        return res.status(500).json({ error: 'The application is not configured correctly.' });
    }
    const ai = new GoogleGenAI({ apiKey: API_KEY });

    const manualTips = {
        [ContentType.TEXT]: [
            "Check for repetitive sentence structures or phrases.",
            "Look for overly complex words used unnecessarily.",
            "Does the text lack a personal voice, emotion, or anecdotes?",
            "Verify factual claims from independent, reputable sources."
        ],
        [ContentType.IMAGE]: [
            "Zoom in on details like hands, teeth, and text in the background.",
            "Examine shadows, reflections, and light sources for consistency.",
            "Look for strange blurring, unnatural textures, or mismatched patterns.",
            "Use a reverse image search to find the image's origin or similar versions."
        ],
        [ContentType.VIDEO]: [
            "Check for unnatural facial movements or blinking patterns.",
            "Listen for robotic-sounding speech or audio that doesn't match the lip movements.",
            "Look for flickering or distortions around the edges of objects or people.",
            "Are there any weird blurs or 'morphing' effects during movement?"
        ] 
    };

    const responseSchema = {
        type: 'OBJECT',
        properties: {
            aiScore: { type: 'NUMBER', description: "A score from 0 (definitely human) to 100 (definitely AI)." },
            reasoning: { type: 'STRING', description: "A brief, one-sentence explanation for the score." },
            evidence: {
                type: 'ARRAY',
                description: "A list of 2-3 bullet points detailing specific evidence found in the content.",
                items: { type: 'STRING' }
            }
        },
        required: ["aiScore", "reasoning", "evidence"],
    };

    try {
        const { type, data, mimeType, fileName } = req.body;

        if (!type || !data) {
            return res.status(400).json({ error: 'Missing type or data in request body.' });
        }
    
        let contents: any;

        if (type === ContentType.TEXT) {
            const systemInstruction = "You are an expert AI content detector. Analyze the following text and determine the probability that it was generated by an AI. Provide a score from 0 to 100 and detailed reasoning in the requested JSON format.";
            contents = { parts: [{ text: systemInstruction }, { text: "Here is the text to analyze:" }, { text: data as string }] };
        } else if (type === ContentType.IMAGE && typeof data === 'string') {
            const systemInstruction = "You are an expert AI-generated image detector. Analyze the following image for signs of AI generation, such as artifacts in hands, text, shadows, or textures. Provide a score from 0 to 100 and detailed reasoning in the requested JSON format.";
            contents = { parts: [{ text: systemInstruction }, { text: "Here is the image to analyze:" }, { inlineData: { mimeType: mimeType, data: data } }] };
        } else if (type === ContentType.VIDEO && Array.isArray(data)) {
            const systemInstruction = "You are an expert AI-generated video detector. I will provide you with a sequence of frames extracted from a video. Analyze these frames as a whole for common signs of AI generation (e.g., flickering, morphing artifacts, unnatural movement, inconsistent details). Provide a single, overall score for the entire video based on these frames and detailed reasoning in the requested JSON format.";
            const parts: any[] = [{ text: systemInstruction }, { text: "Here are the frames to analyze:" }];
            data.forEach(frameBase64 => {
                parts.push({ inlineData: { mimeType: 'image/jpeg', data: frameBase64 } });
            });
            contents = { parts };
        } else {
            return res.status(400).json({ error: "Invalid content type or data format provided." });
        }

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents,
            config: {
                responseMimeType: "application/json",
                responseSchema: responseSchema,
            },
        });

        const jsonText = response.text.trim();
        const result = JSON.parse(jsonText);

        const analysis: ApiDetail[] = [{
            provider: 'Gemini AI',
            score: result.aiScore,
            details: [result.reasoning, ...result.evidence]
        }];
        
        const scanResult: ScanResult = {
            overallScore: parseFloat(result.aiScore.toFixed(2)),
            contentType: type,
            analysis: analysis,
            manualInspectionTips: manualTips[type],
            fileName: fileName,
        };

        return res.status(200).json(scanResult);

    } catch (error: any) {
        console.error("Error in serverless function:", error);
        if (error.message.includes('API key not valid')) {
             return res.status(500).json({ error: 'The configured API key on the server is invalid.'});
        }
        return res.status(500).json({ error: 'An internal server error occurred during analysis.' });
    }
}